### ISSUE TITLE
No Contact Info

### ISSUE THREAD

**Issue by dzoba** [Jon-Biz/simple-static-react-aframe#4]
Hey Jonathan,

Your Github profile says "I'm a javascript developer in San Francisco. I'm looking for contract and full time positions working with React and/or Node.", however, I can't find contact info for you.  If you'd like to get in touch about a React + Firebase position in San Francisco, get in touch!  chris@residenetwork.com

**Comment by Jon-Biz** [comment]
:)

You can reach me at jon-biz-github at elbizri daught com
